### ISSUE TITLE
Error when click on icon in the token controls

### ISSUE THREAD

**Issue by CaosFR** [caewok/fvtt-token-cover#29]
Hi,

After install your module and try to configure it I see a error on the console.

Each time I click on the icon in token controls nothing happens and I can see a error on the console : 

```
Error: An error occurred while rendering CoverEffectsApp 43. (intermediate value)._findStorageDocument is not a function
[Detected 1 package: tokencover(0.9.2)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Hooks.onError#lib-wrapper (listeners.js:140:11)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52)
    at foundry.js:5794:13Caused by: TypeError: An error occurred while rendering CoverEffectsApp 43. (intermediate value)._findStorageDocument is not a function
[Detected 1 package: tokencover(0.9.2)]
    at CoverDFreds._findLocalDocument (cover_unique_effects.js:108:38)
    at get document (AbstractUniqueEffect.js:130:68)
    at get name (AbstractUniqueEffect.js:141:28)
    at CoverEffectsController.js:35:84
    at Map.forEach (<anonymous>)
    at get data (CoverEffectsController.js:35:46)
    at CoverEffectsApp.getData (CoverEffectsApp.js:67:39)
    at CoverEffectsApp._render (foundry.js:5837:29)
    at CoverEffectsApp.render (foundry.js:5792:10)
    at Object.onClick (module.js:118:42)
    at SceneControls._onClickTool (foundry.js:81624:52)
    at HTMLLIElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)
```

Thanks for your help

**Comment by caewok** [comment]
This is a DFred's compatibility issue. Addressed in v0.9.3.
