### ISSUE TITLE
Error when invoc a monster

### ISSUE THREAD

**Issue by CaosFR** [caewok/fvtt-token-cover#39]
Hi,

Each time I invoc a monster a get this error :  

foundry.js:655 Error: Error thrown in hooked function 'refreshToken' for hook 'refreshToken'. Cannot read properties of undefined (reading 'values')
[Detected 1 package: tokencover(0.9.6)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at Token5e.applyRenderFlags (foundry.js:26658:11)
    at #applyRenderFlags (foundry.js:26282:44)
    at mn.emit (TickerListener.ts:71:47)
    at Pt.update (Ticker.ts:427:37)
    at Pt._tick (Ticker.ts:129:22)Caused by: TypeError: Cannot read properties of undefined (reading 'values')
[Detected 1 package: tokencover(0.9.6)]
    at CoverActiveEffect.allOnToken (AbstractUniqueEffect.js:569:51)
    at get _currentCoverEffects (TokenCover.js:138:42)
    at #clearCover (TokenCover.js:417:31)
    at TokenCover.updateCover (TokenCover.js:407:38)
    at TokenCover.tokenMoved (TokenCover.js:374:10)
    at TokenCover.tokenMoved (TokenCover.js:473:22)
    at Object.refreshToken [as fn] (Token.js:206:16)
    at #call (foundry.js:632:20)
    at Hooks.callAll (foundry.js:589:17)
    at Token5e.applyRenderFlags (foundry.js:26658:11)
    at #applyRenderFlags (foundry.js:26282:44)
    at mn.emit (TickerListener.ts:71:47)
    at Pt.update (Ticker.ts:427:37)
    at Pt._tick (Ticker.ts:129:22)

Foundry : v 12
Token-cover : latest
DnD : 3.3.X
Chromium : latest

**Comment by caewok** [comment]
I don't understand what "invoc a monster" means. Also, could you tell me whether you have "Only Use Cover Icons" enabled?

**Comment by CaosFR** [comment]
By invocation, I mean a conjure speel like https://www.dndbeyond.com/spells/2039-conjure-animals

"Only Use Cover Icons" is not enable, why do you say that ?

**Comment by caewok** [comment]
I think v0.9.8 addresses this.
