### ISSUE TITLE
Non-functional on a fresh dnd5e v4.1 world?

### ISSUE THREAD

**Issue by Krigsmaskine** [caewok/fvtt-token-cover#42]
I wanted to test out Alternate Token Cover as dnd5e finally actually does something with their cover status effects programmatically with the newest update, but toggling them on/off as needed is a bit of a hassle.

Opening the module and pressing "reset to dnd5e dmg" and then playing with settings, I can't get Alternate Token Cover to do anything. It doesn't put out any errors in console. Using items with Attack activities to test and I've gone into the settings and just tried to check/uncheck any relevant box to see if I could get some outcome, none seems to have worked. I have not changed any number input or slider-esque fields.

The only errors I can make happen is when enabling debug rays, which to be fair, also looks a little strange? It doesn't seem to be testing rays against my actual targets or NPC actors?
![image](https://github.com/user-attachments/assets/30451207-081d-4ba6-9efe-53f201eebe5a)

The errors regarding the debug ray is  'refreshTokenDebugHook';
foundry.js:655 Error: Error thrown in hooked function 'refreshTokenDebugHook' for hook 'refreshToken'. Cannot read properties of undefined (reading 'length')
[Detected 1 package: tokencover(0.9.7)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at Token5e.applyRenderFlags (foundry.js:26658:11)
    at #applyRenderFlags (foundry.js:26282:44)
    at mn.emit (TickerListener.ts:71:47)
    at Pt.update (Ticker.ts:427:37)
    at Pt._tick (Ticker.ts:129:22)

dnd5e v4.1.1
foundryvtt 12.331

**Comment by caewok** [comment]
A couple things:

1. In v0.9.8, I changed the default cover effects for dnd5e v4 to use the new dnd status effects. To get those, the simplest option is to go to the Cover Book and click "Reset Default Cover." 
2. I cannot figure out where this error is occurring (about undefined reading length). Sorry; the debugging code needs some work as things have migrated over time.
3. Can you paste in a comment screenshots of your ATC settings?
